### ISSUE TITLE
Cannot read property 'contextAsc' of undefined

### ISSUE THREAD

**Issue by nkishorchandra** [HVStechnik/ckeditor-tablesorter#2]
I have included this plugin and added it to my plugins by using following line of code.

CKEDITOR.config.extraPlugins = 'tablesorter';

It is throwing the following error.

Uncaught TypeError: Cannot read property 'contextAsc' of undefined
    at Object.init (plugin.js?t=H8DC:16)
    at Object.<anonymous> (ckeditor.js:255)
    at g (ckeditor.js:236)
    at Array.n (ckeditor.js:236)
    at p (ckeditor.js:237)
    at ckeditor.js:237

Tried with 2 versions (4.7.0 and 4.7.3) but no luck. It would be better to provide an example code in the README section on how this works.

**Comment by HVStechnik** [comment]
Sorry for answering so late. 

I run the plugin with version 4.7.0. Exactly as mentioned you have to add 'tablesorter' to the extraPlugins value of your config.js.

Your error seems to be related to the translation of the labels. Do you run ckeditor in a particular language, for which I might not have a language file yet?

**Comment by amikrage** [comment]
Опечатка в английском языковом файле
CKEDITOR.plugins.setLang( 'tablesorter', de', {        
        contextAsc: 'Sort ascending',
        contextDesc: 'Sort descending',
} );
de менять на en, ну или создаём свой язык.

**Comment by HVStechnik** [comment]
First: You're lacking an " ' " before the "de" in your last comment.
Second: You're defining a German language setting. If you're not using CKEditor in German, but in your own language, you have to change the 'de' above into your own language code.
